version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 5000:8000
    volumes:
      - ./src:/src
    links:
      - database:db
  database:
    image: mariadb:10.3
    restart: always
    ports:
      - 3301:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - 8181:80
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    depends_on:
      - database
